### ISSUE TITLE
All day events not recognized

### ISSUE THREAD

**Issue by dlichtistw** [irgangla/icalevents#22]
I am parsing an iCalendar from Google calendar, but icalevents fails to recognize all day events. They are imported, but with `all_day == False`.

I think, I tracked down the problem to one line in the `create_event` method.
https://github.com/irgangla/icalevents/blob/652f522e578183908f6a7936f0ac5b291e93c6db/icalevents/icalparser.py#L161
But the type of all day events' start attribute is `date`, not `datetime.date`. Hence, the flag should probably be set as
`event.all_day = type(component.get('dtstart').dt) is date`

**Comment by dlichtistw** [comment]
I'm still not fluent in Git. Hopefully, this is the right procedure.
With this little fix, I get successful distinction between all day and part day events (in my test case).

**Comment by cun3yt** [comment]
Is this issue resolved? When I try with this all day recurring event from Google Calendar, it gives `False` for `event.all_day` on v0.1.13.

```
BEGIN:VEVENT
DTSTART;VALUE=DATE:20181030
DTEND;VALUE=DATE:20181031
RRULE:FREQ=WEEKLY;BYDAY=TU
DTSTAMP:20181113T191224Z
UID:3k9i34bf1h2q9fq30gqsk8dcqj@google.com
CREATED:20181113T191200Z
DESCRIPTION:
LAST-MODIFIED:20181113T191214Z
LOCATION:
SEQUENCE:3
STATUS:CONFIRMED
SUMMARY:Game Tag Day
TRANSP:TRANSPARENT
END:VEVENT
```

```python
ipdb> event.summary
'Game Tag Day'
ipdb> event.all_day
False
ipdb> event.start
datetime.datetime(2018, 11, 13, 0, 0, tzinfo=tzfile('/usr/share/zoneinfo/America/Los_Angeles'))
ipdb> event.end
datetime.datetime(2018, 11, 14, 0, 0, tzinfo=tzfile('/usr/share/zoneinfo/America/Los_Angeles'))
```

**Comment by cun3yt** [comment]
Apparently recurring all day events are marked wrong, I will open an issue for it.
