### ISSUE TITLE
Related Project?

### ISSUE THREAD

**Issue by niccokunzmann** [irgangla/icalevents#50]
Hi, I created a library to get all events within a certain time frame.
I do not know if yours is related.
https://github.com/niccokunzmann/python-recurring-ical-events

**Comment by irgangla** [comment]
Hi, it seems to be a quite similar use case. I tried to get all events for a given time span to display it on an info display.

**Comment by niccokunzmann** [comment]
Thanks for the confirmation. I linked to it so people have a better choice.
https://github.com/niccokunzmann/python-recurring-ical-events#related-projects
